<?php

namespace Database\Seeders\Crm;

use App\Models\Crm\Company;
use App\Models\CRM\CompanyAddress;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $companies = [
            ['name' => 'PT Persada', 'industry_id' => 25],
            ['name' => 'Overseas Clients', 'industry_id' => 189],
            ['name' => 'UKRI', 'industry_id' => 58],
            ['name' => 'ITENAS', 'industry_id' => 58],
            ['name' => 'BNPB', 'industry_id' => 84],
            ['name' => 'IDI', 'industry_id' => 114],
            ['name' => 'PT HM Sampoerna', 'industry_id' => 176],
            ['name' => 'PT Perkebunan Sumatera Utara', 'industry_id' => 4],
            ['name' => 'Kementerian Kelautan dan Perikanan', 'industry_id' => 84],
            ['name' => 'Borma', 'industry_id' => 158],
            ['name' => 'AHM', 'industry_id' => 13],
            ['name' => 'BIN', 'industry_id' => 51],
            ['name' => 'Kominfo', 'industry_id' => 84],
            ['name' => 'Jagojek', 'industry_id' => 190],
            ['name' => 'CV Jaya Indonesia Prestasi', 'industry_id' => 58],
            ['name' => 'Bajaga', 'industry_id' => 158],
            ['name' => 'Bank Mandiri', 'industry_id' => 14],
            ['name' => 'Panasonic', 'industry_id' => 42],
            ['name' => 'Republikorp', 'industry_id' => 158],
            ['name' => 'Kementerian Dalam Negri', 'industry_id' => 84],
            ['name' => 'Kementerian PUPR', 'industry_id' => 84],
            ['name' => 'Coway', 'industry_id' => 42],
            ['name' => 'Pusat Intel Angkatan Darat', 'industry_id' => 51],
            ['name' => 'Adamasanya', 'industry_id' => 188],
            ['name' => 'Badan Gizi Nasional', 'industry_id' => 84],
            ['name' => 'ALV', 'industry_id' => 191],
        ];

        foreach ($companies as $c) {
            $company = Company::firstOrCreate(
                ['name' => $c['name']], // kunci uniknya by name
                [
                    'ulid' => (string) Str::ulid(),
                    'code' => null, // nanti diisi setelah create (biar bisa pastikan unik)
                    'status' => 'active',
                    'industry_id' => $c['industry_id'],
                    'source_id' => 5,
                    'tags' => ['Customer'],
                ]
            );
            // Isi code hanya kalau belum ada
            if (empty($company->code)) {
                $company->code = $this->makeCompanyCode($company->name);
                $company->save();
            }
            // create company address
            $company->companyAddresses()->firstOrCreate(
                ['is_default' => true],
                [
                    'address_line1' => null,
                    'country_id' => 103,
                    'state_id' => null,
                    'city_id' => null,
                    'postal_code' => null,
                ]
            );
        }
        $leads = [
            [
                "name" => "GRAB",
                "industry_id" => 191,
                "email" => "support.id@grab.com",
                "website" => "grab.com",
                "address_line1" => "South Quarter Tower C, 7th Floor & Mezzanine, Jl. R.A. Kartini Kav. 8, Cilandak Barat, Cilandak",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12430",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 252,
                "name" => "MNC Group",
                "email" => "corsec.mncmedia@mncgroup.com",
                "website" => "www.mncgroup.com",
                "address_line1" => null,
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10340",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 131,
                "name" => "PT Snapsindo Tunggal Putra",
                "email" => null,
                "website" => null,
                "address_line1" => "Bintaro Business Centre, Jl. RC Veteran Raya No. 1, Bintaro, Pesanggrahan",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12330",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 193,
                "name" => "MyPlay",
                "email" => "hi@myplay.com",
                "website" => "www.myplay.com",
                "address_line1" => "Jl. Tomang Asli No. 33",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11430",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 194,
                "name" => "PT Global Integrasi Gemilang (Lokerlink)",
                "email" => "customer.support@lokerlink.com",
                "website" => "www.lokerlink.com",
                "address_line1" => "The H Tower Building, 11th Floor Unit D, Jl. HR Rasuna Said Kav.20 Blok X-10, Kuningan",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12940",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 195,
                "name" => "PT Jalin Pembayaran Nusantara (Jalin.co.id)",
                "email" => "corporate@jalin.co.id",
                "website" => "www.jalin.co.id",
                "address_line1" => "Menara Dea Tower 1 Lantai 2, Jalan Mega Kuningan Barat IX Kav.E.4.3 No.1",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12950",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 196,
                "name" => "BINUS University",
                "email" => "infobinus@binus.edu",
                "website" => "binus.ac.id",
                "address_line1" => "Jl. K.H. Syahdan No. 9, Kemanggisan, Palmerah",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11480",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 197,
                "name" => "PT. TIENS Indonesia Logistic Trading",
                "email" => "cs.tiens.indonesia@gmail.com",
                "website" => "tiens.co.id",
                "address_line1" => "Rukan Multi Guna 5PQR, Jl. Rajawali Selatan Raya Blok C5 No.2, Pademangan Timur, Pademangan",
                "city_id" => "Jakarta Utara",
                "state_id" => "DKI Jakarta",
                "postal_code" => "14410",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 198,
                "name" => "Wall Street English",
                "email" => "communications@wallstreetenglish.co.id",
                "website" => "wallstreetenglish.co.id",
                "address_line1" => "Jl. Jenderal Sudirman, RT.5/RW.3, Senayan, Kebayoran Baru",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12190",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 199,
                "name" => "Kbr.id",
                "email" => "lpse@kbr.id",
                "website" => "kbr.id",
                "address_line1" => "Hayam Wuruk Tower Lantai 10, Jl. Hayam Wuruk No. 103, RT.4/RW.9, Taman Sari",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11160",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 200,
                "name" => "Bank Sahabat Sampoerna",
                "email" => "info@banksampoerna.com",
                "website" => "www.banksampoerna.com",
                "address_line1" => "Sampoerna Strategic Square, North Tower, Mezzanine Floor, Jl. Jend. Sudirman Kav. 45",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12930",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 201,
                "name" => "Ajaib",
                "email" => "support@ajaib.co.id",
                "website" => "ajaib.co.id",
                "address_line1" => "Neo Soho @ Podomoro City Lantai 30-03, Jl. Letjen S Parman Kav. 28, Grogol Petamburan",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 202,
                "name" => "combiphar",
                "email" => "nurhita.anggraeni@combiphar.com",
                "website" => "www.combiphar.com",
                "address_line1" => "Office 8 Building, 35th Floor, Jl. Jenderal Sudirman Kav. 52-53, SCBD Lot 28",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12190",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 203,
                "name" => "Dexa Medica",
                "email" => "info@dexagroup.com",
                "website" => "www.dexagroup.com",
                "address_line1" => "Titan Center, 3rd Floor, Jalan Boulevard Bintaro, Block B7/B1 No. 5, Bintaro Jaya, Sector 7",
                "city_id" => "Tangerang",
                "state_id" => "Banten",
                "postal_code" => "15424",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 204,
                "name" => "Darya Varia",
                "email" => "info@darya-varia.com",
                "website" => "www.darya-varia.com",
                "address_line1" => "South Quarter Tower C, 18th-19th Floor, Jl. R.A. Kartini Kav. 8",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12430",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 187,
                "name" => "Biofarma Tbk",
                "email" => "mail@biofarma.co.id",
                "website" => "www.biofarma.co.id",
                "address_line1" => "Jl. Pasteur No. 28",
                "city_id" => "Bandung",
                "state_id" => "Jawa Barat",
                "postal_code" => "40161",
                "country_id" => 103,
                "website_procurement" => "https://vendors.biofarma.co.id/",
                "email_procurement" => "mail@biofarma.co.id"
            ],
            [
                "industry_id" => 205,
                "name" => "Decathlon Indonesia",
                "email" => "contact.indonesia@decathlon.com",
                "website" => "www.decathlon.co.id",
                "address_line1" => "Jl. Metro Pondok Indah Blk. BB No. 3, Pondok Pinang, Kebayoran Lama",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12310",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 206,
                "name" => "Persis Solo",
                "email" => "media@persissolo.id",
                "website" => "www.persissolo.id",
                "address_line1" => "Jl. Dr. Sutomo No. 8-10, Sriwedari, Laweyan",
                "city_id" => "Surakarta",
                "state_id" => "Jawa Tengah",
                "postal_code" => "57141",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 207,
                "name" => "OMNI Hospital",
                "email" => "corsec@omni-hospitals.com",
                "website" => "www.omni-hospitals.com",
                "address_line1" => "Jl. Pulomas Barat VI No. 20, Kayu Putih, Pulo Gadung",
                "city_id" => "Jakarta Timur",
                "state_id" => "DKI Jakarta",
                "postal_code" => "13210",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 208,
                "name" => "Deloitte Indonesia",
                "email" => "iddttl@deloitte.com",
                "website" => "www.deloitte.com",
                "address_line1" => "The Plaza Office Tower, 32nd Floor, Jl. M.H. Thamrin Kav. 28-30",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10350",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 209,
                "name" => "Indonesia Power",
                "email" => "info@plnipservices.co.id",
                "website" => "www.plnipservices.co.id",
                "address_line1" => "Jl. Jend. Gatot Subroto Kav. 18, Setiabudi",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 210,
                "name" => "ASEAN",
                "email" => "public@asean.org",
                "website" => "asean.org",
                "address_line1" => "70A Jalan Sisingamangaraja",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12110",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 211,
                "name" => "Astra Digital International",
                "email" => "hello@astradigital.id",
                "website" => "astradigital.id",
                "address_line1" => "Altira Business Park, Growth Tower Lantai 19, Jl. Yos Sudarso Kav. 85 No.10, Sunter Jaya, Tanjung Priok",
                "city_id" => "Jakarta Utara",
                "state_id" => "DKI Jakarta",
                "postal_code" => "14350",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 212,
                "name" => "Jatelindo",
                "email" => "support@jatelindo.co.id",
                "website" => "jatelindo.co.id",
                "address_line1" => "Mayapada Tower 2 Lantai 11, Jl. Jend. Sudirman Kav. 27",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12920",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 213,
                "name" => "PT Wide & Pin",
                "email" => "widepin@widepin.com",
                "website" => "widepin.com",
                "address_line1" => null,
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 214,
                "name" => "Telkom Medika",
                "email" => "corpsec@telkomedika.co.id",
                "website" => "telkomedika.co.id",
                "address_line1" => null,
                "city_id" => null,
                "state_id" => null,
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 215,
                "name" => "Shafiq",
                "email" => "salam@shafiq.id",
                "website" => "www.shafiq.id",
                "address_line1" => "Graha Niaga Thamrin, Jl. K.H. Mas Mansyur Kav. 121",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 216,
                "name" => "Alami Sharia",
                "email" => "support@alamisharia.co.id",
                "website" => "alamisharia.co.id",
                "address_line1" => "Plaza 89, Kav. X7 No. 6, Jl. HR Rasuna Said",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12940",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 282,
                "name" => "Indosat",
                "email" => "care@im3.id",
                "website" => "ioh.co.id",
                "address_line1" => "Jl. Medan Merdeka Barat No. 21",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10110",
                "country_id" => 103,
                "website_procurement" => "https://digitalpartnerships.ioh.co.id",
                "email_procurement" => null
            ],
            [
                "industry_id" => 217,
                "name" => "Hijau Digital",
                "email" => "info@hijaudigital.com",
                "website" => "hijaudigital.com",
                "address_line1" => "The City Tower, Lantai 12A, Jl. M.H. Thamrin No. 81",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10310",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 211,
                "name" => "Sentuh Digital",
                "email" => "sales@sentuh.id",
                "website" => "www.sentuh.id",
                "address_line1" => "Lengkong Gudang Timur, Kec. Serpong",
                "city_id" => "Tangerang Selatan",
                "state_id" => "Banten",
                "postal_code" => "15310",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 218,
                "name" => "Amartha Finance",
                "email" => "support@amartha.com",
                "website" => "amartha.com",
                "address_line1" => "Jl. TB Simatupang Kav. 18, Cilandak Barat",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12430",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 219,
                "name" => "Duvaderm",
                "email" => "sales@duvaderm.com",
                "website" => "duvaderm.com",
                "address_line1" => "Rukan Grand Aries Niaga, Jl. Taman Aries Blok E1-3R, Meruya Utara, Kembangan",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11620",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 220,
                "name" => "SOS",
                "email" => "marketing@alsokbass.co.id",
                "website" => "www.sos.co.id",
                "address_line1" => "Gedung SOS, Jl. Tanah Abang II No. 49-51",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10160",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 283,
                "name" => "Badan Pelayanan Perizinan dan Penanaman Modal Daerah (BP3MD)",
                "email" => "bp3md@sumselprov.go.id",
                "website" => "bp3md.co.id",
                "address_line1" => "Jalan Jenderal Sudirman No. 90 KM 4,5",
                "city_id" => "Palembang",
                "state_id" => "Sumatera Selatan",
                "postal_code" => "30128",
                "country_id" => 103,
                "website_procurement" => "https://lpse.sumselprov.go.id",
                "email_procurement" => null
            ],
            [
                "industry_id" => 221,
                "name" => "PT Terralogiq Integrasi Solusi",
                "email" => "info@terralogiq.com",
                "website" => "terralogiq.com",
                "address_line1" => null,
                "city_id" => null,
                "state_id" => null,
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 222,
                "name" => "PT Dotcom Indonesia",
                "email" => "info@dotcom.id",
                "website" => "www.dotcom.id",
                "address_line1" => "Sedayu Square G/08, Jl. Outer Ring Road Lingkar Luar, Cengkareng",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11730",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 223,
                "name" => "PT PLN (Persero)",
                "email" => "pln123@pln.co.id",
                "website" => "web.pln.co.id",
                "address_line1" => "Jalan Trunojoyo Blok M – I No. 135, Kebayoran Baru",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12160",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 131,
                "name" => "PT Ahendo Inti Perdana",
                "email" => null,
                "website" => "ahendo.com",
                "address_line1" => null,
                "city_id" => null,
                "state_id" => null,
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 224,
                "name" => "OLX Indonesia",
                "email" => "cs@olx.co.id",
                "website" => "www.olx.co.id",
                "address_line1" => "Jl. Ampera Raya No. 137, Ragunan, Pasar Minggu",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12560",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 188,
                "name" => "LKPP",
                "email" => "layanan@lkpp.go.id",
                "website" => "www.lkpp.go.id",
                "address_line1" => "Gedung LKPP, Jl. Epicentrum Tengah Lot 11B, Kuningan",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12940",
                "country_id" => 103,
                "website_procurement" => "https://inaproc.id/",
                "email_procurement" => "helpdesk.pspse@lkpp.go.id"
            ],
            [
                "industry_id" => 225,
                "name" => "PT Konimex",
                "email" => "customer_service@konimex.com",
                "website" => "www.konimex.com",
                "address_line1" => "Desa Sanggrahan, Grogol",
                "city_id" => "Sukoharjo",
                "state_id" => "Jawa Tengah",
                "postal_code" => "57552",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 226,
                "name" => "PT Indomedia Group",
                "email" => "info@indomedia.net.id",
                "website" => "indomedia.net.id",
                "address_line1" => "Avenue 88, 1st Floor, Jl. Raya Kuta No. 88",
                "city_id" => "Badung",
                "state_id" => "Bali",
                "postal_code" => "80361",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 227,
                "name" => "Mandiri Sekuritas",
                "email" => "care_center@mandirisek.co.id",
                "website" => "www.mandirisekuritas.co.id",
                "address_line1" => "Plaza Mandiri, Jl. Jenderal Gatot Subroto Kav. 36-38",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12190",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 282,
                "name" => "PT XL Axiata Tbk",
                "email" => "corpcomm@xl.co.id",
                "website" => "www.xlaxiata.co.id",
                "address_line1" => "XL Axiata Tower, Jl. H.R. Rasuna Said X5 Kav. 11-12, Kuningan Timur, Setiabudi",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12950",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 228,
                "name" => "PT Aliansi Teknologi Indonesia",
                "email" => "help@dana.id",
                "website" => "www.dana.id",
                "address_line1" => "Capital Place, 18th Floor, Jl. Jend. Gatot Subroto Kav. 18, Kuningan Barat",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12710",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 229,
                "name" => "PT Asian Rainbow Posters",
                "email" => null,
                "website" => "www.rainbow.co.id",
                "address_line1" => "Kawasan Industri Pulogadung, Jl. Rawagelam V No. 8",
                "city_id" => "Jakarta Timur",
                "state_id" => "DKI Jakarta",
                "postal_code" => "13930",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 189,
                "name" => "PT. Bali Towerindo Sentra, Tbk",
                "email" => "corporate.secretary@balitower.co.id",
                "website" => "www.balitower.co.id",
                "address_line1" => "The Autograph Tower, 77th floor, Thamrin Nine Complex, Jl. M.H. Thamrin No.10",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10230",
                "country_id" => 103,
                "website_procurement" => "https://e-submission.balitower.co.id",
                "email_procurement" => "vendor.management@balitower.co.id"
            ],
            [
                "industry_id" => 230,
                "name" => "Yayasan Aksi Cepat Tanggap (ACT)",
                "email" => "info@act.id",
                "website" => "act.id",
                "address_line1" => "Menara 165 Office Tower, Lt. 11, Jl. TB Simatupang Kav. 1, Cilandak Timur",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12560",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 231,
                "name" => "Koperasi Telekomunikasi Selular (KISEL)",
                "email" => "corporate_communications@kiselgroup.com",
                "website" => "kiselgroup.com",
                "address_line1" => "Kisel Hub, Jl. TB Simatupang No. 4, Cilandak",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12430",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 232,
                "name" => "PT Jelajah Data Semesta",
                "email" => "support@jelajahdata.co.id",
                "website" => "jelajahdata.co.id",
                "address_line1" => "Komp. Ruko Mega Grosir Cempaka Mas Blok A No. 29",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10640",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 99,
                "name" => "Jasa Raharja Putera",
                "email" => "pusat@jrp.co.id",
                "website" => "jrp.co.id",
                "address_line1" => "Jl. TB Simatupang Kav. 1, Cilandak Timur",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12560",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 233,
                "name" => "PT Acer Indonesia",
                "email" => "acerpeduli@acer.com",
                "website" => "www.acer.com",
                "address_line1" => "Jl. Gunung Sahari Raya I",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => "14420",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 234,
                "name" => "PT Persita Tangerang Raya",
                "email" => "admin@persitafc.com",
                "website" => "www.persitafc.com",
                "address_line1" => "Jl. Kelapa Puan Raya Blok AF1 No. 1, Kelapa Dua (Gading Serpong)",
                "city_id" => "Kabupaten Tangerang",
                "state_id" => "Banten",
                "postal_code" => "15811",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 235,
                "name" => "PT Moladin Digital Indonesia",
                "email" => "hello@moladin.com",
                "website" => "moladin.com",
                "address_line1" => "Citra Tower Lt. 10 Unit G, Jl. Benyamin Suaeb Kav. A6, Kemayoran",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10630",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 236,
                "name" => "Badan Ekonomi Kreatif",
                "email" => "hub@ekraf.go.id",
                "website" => "www.bekraf.go.id",
                "address_line1" => "Autograph Tower Lantai 33, Jl. M.H. Thamrin No.10, Kebon Melati, Tanah Abang",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10230",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 237,
                "name" => "Badan Standarisasi Nasional",
                "email" => "bsn@bsn.go.id",
                "website" => "bsn.go.id",
                "address_line1" => "Jl. Kuningan Barat Raya No. 1A, Kuningan Barat, Mampang Prapatan",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12710",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 238,
                "name" => "PT Ciputra Nusantara",
                "email" => "career@ciputra.com",
                "website" => "ciputrarecruitmentcenter.com",
                "address_line1" => "Ciputra World 1, 13th Floor, Jl. Prof. Dr. Satrio Kav. 3-5",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12940",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 239,
                "name" => "Chicago Capital Limit",
                "email" => "info@chi-cap.com",
                "website" => "www.chi-cap.com",
                "address_line1" => "135 S LaSalle St Suite 4200",
                "city_id" => "Chicago",
                "state_id" => "Illinois",
                "postal_code" => "60603",
                "country_id" => 840,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 240,
                "name" => "PT Douva Affala International",
                "email" => "hrd@douvagroup.com",
                "website" => "www.vanaya.co.id",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12540",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 241,
                "name" => "PT Edukasi Anak Indonesia",
                "email" => "abangmantek4@gmail.com",
                "website" => "www.e-abangmantek.com",
                "address_line1" => null,
                "city_id" => "Sukabumi",
                "state_id" => "Jawa Barat",
                "postal_code" => "43156",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 242,
                "name" => "PT Sekolah Integrasi Digital",
                "email" => "suaramu@sekolahmu.co.id",
                "website" => "sekolah.mu",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12560",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 243,
                "name" => "BPJSTKU",
                "email" => "care@bpjsketenagakerjaan.go.id",
                "website" => "www.bpjsketenagakerjaan.go.id",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12710",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 244,
                "name" => "Tower Bersama Infrastructure Tbk PT",
                "email" => "corporate.secretary@tower-bersama.com",
                "website" => "www.tower-bersama.com",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12940",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 131,
                "name" => "PT Mest Indonesiy",
                "email" => "informasi@mestindo.com",
                "website" => "mestindo.com",
                "address_line1" => null,
                "city_id" => "Medan",
                "state_id" => "Sumatera Utara",
                "postal_code" => "20235",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 245,
                "name" => "Balai Sertifikasi Elektronik",
                "email" => "info.bsre@bssn.go.id",
                "website" => "bsre.bssn.go.id",
                "address_line1" => null,
                "city_id" => "Depok",
                "state_id" => "Jawa Barat",
                "postal_code" => "16516",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 246,
                "name" => "PT Pegadaian (Persero)",
                "email" => "customer.care@pegadaian.co.id",
                "website" => "pegadaian.co.id",
                "address_line1" => null,
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10430",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 247,
                "name" => "Spare",
                "email" => "info@paywithspare.com",
                "website" => "www.paywithspare.com",
                "address_line1" => null,
                "city_id" => "Cairo",
                "state_id" => "Egypt",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 248,
                "name" => "PT Aplikasi Karya Anak Bangsa",
                "email" => "corpsecretary@gotocompany.com",
                "website" => "www.gojek.com",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12160",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 249,
                "name" => "KlarSmile",
                "email" => "care@klarsmile.com",
                "website" => "www.klarsmile.com",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12240",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 250,
                "name" => "Anugrah Fatahillah Nibras",
                "email" => "info@nbrs.co.id",
                "website" => "nbrscorp.co.id",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12550",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 251,
                "name" => "PAS Technologies",
                "email" => "cs@pashouses.id",
                "website" => "pashouses.id",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12930",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 131,
                "name" => "PT Wahana Media Cakrawala (Doki)",
                "email" => "hello@doki.id",
                "website" => "doki.id",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 253,
                "name" => "Storial.co",
                "email" => "contact@storial.co",
                "website" => "storial.co",
                "address_line1" => null,
                "city_id" => null,
                "state_id" => null,
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 254,
                "name" => "TigerGraph",
                "email" => "info@tigergraph.com",
                "website" => "www.tigergraph.com",
                "address_line1" => null,
                "city_id" => null,
                "state_id" => null,
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 255,
                "name" => "Aseanindo",
                "email" => null,
                "website" => "aseanindo.com",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12920",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 256,
                "name" => "Klinik Makmur Jaya",
                "email" => null,
                "website" => "klinikmakmurjaya.blogspot.com",
                "address_line1" => null,
                "city_id" => "Mojokerto",
                "state_id" => "Jawa Timur",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 257,
                "name" => "Orang Tua Group",
                "email" => "customercare@ot.id",
                "website" => "www.ot.id",
                "address_line1" => null,
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11740",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 258,
                "name" => "KOMINFO - IGRS",
                "email" => "humas@mail.kominfo.go.id",
                "website" => "www.komdigi.go.id",
                "address_line1" => "Jl. Medan Merdeka Barat No. 9",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10110",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 259,
                "name" => "Univ. Lambung Mangkurat",
                "email" => "ppid@ulm.ac.id",
                "website" => "ulm.ac.id",
                "address_line1" => "Jl. Brigjen H. Hasan Basri, Kayu Tangi",
                "city_id" => "Banjarmasin",
                "state_id" => "Kalimantan Selatan",
                "postal_code" => "70123",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 260,
                "name" => "Sekretariat Kabinet",
                "email" => "humas@setkab.go.id",
                "website" => "setkab.go.id",
                "address_line1" => "Jl. Veteran No. 18",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10110",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 261,
                "name" => "PT Orion Beauty International",
                "email" => null,
                "website" => "snpcos.co.id",
                "address_line1" => "Revenue Tower, District 8, Jl. Jendral Sudirman No.52-53, Level 15",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12190",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 262,
                "name" => "PT Hello Kreasi Indonesia",
                "email" => null,
                "website" => "www.hiapp.id",
                "address_line1" => null,
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 263,
                "name" => "Wintermar",
                "email" => null,
                "website" => "www.wintermar.com",
                "address_line1" => "Office 88 Kota Kasablanka, Unit 9th Floor Unit G, Jl. Casablanca Raya Kav. 88",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12870",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 264,
                "name" => "Talent Growth",
                "email" => null,
                "website" => "www.talentgrowth.id",
                "address_line1" => "Pogung Rejo RT 14 RW 51 No. 412, Sinduadi, Mlati",
                "city_id" => "Sleman",
                "state_id" => "D.I. Yogyakarta",
                "postal_code" => "55284",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 190,
                "name" => "Intiland Development",
                "email" => "info@pupuk-indonesia.com",
                "website" => "www.intiland.com",
                "address_line1" => "Jl. Taman Anggrek No.2 RW 08, Kemanggisan",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11480",
                "country_id" => 103,
                "website_procurement" => "https://eprocurement.pupuk-indonesia.com/",
                "email_procurement" => "vm.eproc@pupuk-indonesia.com"
            ],
            [
                "industry_id" => 265,
                "name" => "Samitra Gantari Pariwara",
                "email" => "info@inovasi.or.id",
                "website" => "samitra.co.id",
                "address_line1" => "Summitmas II, Lantai 4, Jl. Jenderal Sudirman Kav. 61-62",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12190",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 131,
                "name" => "Inovasi Pilihan Indonesia",
                "email" => null,
                "website" => "inovasicad.id",
                "address_line1" => null,
                "city_id" => null,
                "state_id" => null,
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 266,
                "name" => "PK Entertainment",
                "email" => null,
                "website" => "www.pk-ent.com",
                "address_line1" => "Kavling Komersial Alam Sutera, Jalan Alam Utama Kav. 35, Alam Sutera",
                "city_id" => "Tangerang",
                "state_id" => "Banten",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 267,
                "name" => "Digital Muslim Program",
                "email" => null,
                "website" => "tcpinternusa.com",
                "address_line1" => "Grand Melia Hotel Lt.5, Jl. H.R. Rasuna Said Kav. X-0, Kuningan",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12950",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 268,
                "name" => "Pupuk Indonesia",
                "email" => null,
                "website" => "www.pupuk-indonesia.com",
                "address_line1" => null,
                "city_id" => "Brooklyn",
                "state_id" => "New York",
                "postal_code" => "11205",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 269,
                "name" => "Asia Chart Indonesia",
                "email" => "customercare@21express.co.id",
                "website" => "www.21express.co.id",
                "address_line1" => "Jl. Raya Bekasi Km. 19 No. 1-3, Pulo Gadung",
                "city_id" => "Jakarta Timur",
                "state_id" => "DKI Jakarta",
                "postal_code" => "13260",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 270,
                "name" => "PT Sehat Maju Perkasa",
                "email" => "partner@talentgrowth.id",
                "website" => "www.talentgrowth.id",
                "address_line1" => null,
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => null,
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 238,
                "name" => "PT TCP Internusa",
                "email" => "info@intiland.com",
                "website" => "tcpinternusa.com",
                "address_line1" => "Intiland Tower, Penthouse Floor, Jl. Jendral Sudirman 32",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10220",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 271,
                "name" => "Klevahealth",
                "email" => "marketing@wintermar.com",
                "website" => "www.klevahealth.com",
                "address_line1" => "Jl. Kebayoran Lama No. 155",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11560",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 272,
                "name" => "Globalindo Dua Satu Indonesia",
                "email" => "info@samitra.co.id",
                "website" => "samitra.co.id",
                "address_line1" => "Multika Building, Jl. Mampang Prapatan Raya No.71-73 RT1 RW1, Tegal Parang, Mampang Prapatan",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12790",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 273,
                "name" => "Brainmatics",
                "email" => "info@brainmatics.com",
                "website" => "brainmatics.id",
                "address_line1" => "Menara Bidakara 1, Lantai 2, Suite 0205, Jl. Jend. Gatot Subroto Kav. 71-73, Pancoran",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12870",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 274,
                "name" => "PT Gerai Cepat Untung (GoToko)",
                "email" => "cs@gotoko.co.id",
                "website" => "www.gotoko.co.id",
                "address_line1" => "Gedung Pasaraya Blok M Gedung B Lantai 6 dan 7, Jl. Iskandarsyah II No. 2",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12160",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 275,
                "name" => "Zenius Education",
                "email" => "cs@zenius.com",
                "website" => "www.zenius.net",
                "address_line1" => "Plaza Aminta Floor 5/504, Jalan TB Simatupang Kav. 10 RT.006, Pondok Pinang, Kebayoran Lama",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12310",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 276,
                "name" => "Hanwa Indonesia",
                "email" => null,
                "website" => "www.hanwa.co.id",
                "address_line1" => "Jakarta Mori Tower Lt. 15, Jl. Jend. Sudirman Kav.40-41, Bend. Hilir, Kec. Tanah Abang",
                "city_id" => "Jakarta Pusat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "10210",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 277,
                "name" => "PT Paragon Technology and Innovation",
                "email" => "customercare@paracorpgroup.com",
                "website" => "www.paragon-innovation.com",
                "address_line1" => "Jalan Swadarma Raya Kampung Baru IV No. 1",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12250",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 278,
                "name" => "Cobra Dental",
                "email" => "care@cobradental.co.id",
                "website" => "www.cobradental.co.id",
                "address_line1" => "Jl. Warung Jati Barat No.22C, RW.11, Pejaten Barat, Kec. Pasar Minggu",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12540",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 279,
                "name" => "Arthatech",
                "email" => "sales@arthatech.id",
                "website" => "www.arthatech.id",
                "address_line1" => "Komp. Golden Plaza Blok J34, Jl. RS Fatmawati No. 15, Gandaria Selatan",
                "city_id" => "Jakarta Selatan",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12420",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 280,
                "name" => "Adrena Tech",
                "email" => "support@adrena.id",
                "website" => "adrena.id",
                "address_line1" => "Infiniti Office, Permata Regency D/37, Kembangan",
                "city_id" => "Jakarta Barat",
                "state_id" => "DKI Jakarta",
                "postal_code" => "11630",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ],
            [
                "industry_id" => 281,
                "name" => "Boston Consulling Group",
                "email" => null,
                "website" => "www.bcg.com",
                "address_line1" => "Sampoerna Strategic Square, 19th Floor, Jl. Jenderal Sudirman Kav. 45-46",
                "city_id" => "Jakarta",
                "state_id" => "DKI Jakarta",
                "postal_code" => "12930",
                "country_id" => 103,
                "website_procurement" => null,
                "email_procurement" => null
            ]
        ];
        foreach ($leads as $lead) {
            $leadd = Company::firstOrCreate(
                ['name' => $lead['name']], // kunci uniknya by name
                [
                    'ulid' => (string) Str::ulid(),
                    'code' => null, // nanti diisi setelah create (biar bisa pastikan unik)
                    'email' => $lead['email'],
                    'website' => $lead['website'],
                    'website_procurement' => $lead['website_procurement'],
                    'email_procurement' => $lead['email_procurement'],
                    'industry_id' => $lead['industry_id'],
                    'source_id' => 5,
                    'status' => 'active',
                    'tags' => ['Cold Lead'],
                ]
            );
            // Isi code hanya kalau belum ada
            if (empty($leadd->code)) {
                $leadd->code = $this->makeCompanyCode($leadd->name);
                $leadd->save();
            }
            $leadd->companyAddresses()->firstOrCreate(
                [
                    'address_line1' => $lead['address_line1'] ?? null,
                    'country_id'    => 103,
                    'state_id'      => \App\Models\Regional\State::where('name', $lead['state_id'])->first()->id ?? null,
                    'city_id'       => \App\Models\Regional\City::where('name', $lead['city_id'])->first()->id ?? null,
                    'postal_code'   => $lead['postal_code'] ?? null,
                    'is_default'    => true,
                ]
            );
        }
    }
    private function makeCompanyCode(string $companyName): string
    {
        $base = Str::upper(trim($companyName));
        $hash = strtoupper(substr(md5($base), 0, 6));

        return "CMP-{$hash}";
    }
}
